[package]
name = "jueming-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
jueming-core = { path = "../jueming-core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true
