packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.42'
  - '@vue/compiler-dom@3.5.42'
  - '@vue/compiler-sfc@3.5.42'
  - '@vue/compiler-ssr@3.5.42'
  - '@vue/reactivity@3.5.42'
  - '@vue/runtime-core@3.5.42'
  - '@vue/runtime-dom@3.5.42'
  - '@vue/server-renderer@3.5.42'
  - '@vue/shared@3.5.42'
  - vue-router@5.3.0
  - vue@3.5.42
