<script setup lang="ts">
import { computed, ref } from "vue";
import { useVirtualizer } from "@tanstack/vue-virtual";
import type { ResearchSummary } from "../../domain/research-types";
import { t } from "../../i18n";

const props = defineProps<{ summary: ResearchSummary; activeGroup: string | null; writable: boolean; busy: boolean; translationLabel: string }>();
const emit = defineEmits<{ filter: [name: string | null]; merge: [from: string, to: string] }>();
const denominator = ref<"confirmed" | "all">("confirmed");
const groupSearch = ref("");
const mergeFrom = ref<string | null>(null);
const groupViewport = ref<HTMLElement | null>(null);
const grouped = computed(() => {
  const groups = new Map<string, { name: string; count: number; strategies: Map<string, number> }>();
  for (const entry of props.summary.groups) {
    const group = groups.get(entry.name) ?? { name: entry.name, count: 0, strategies: new Map<string, number>() };
    group.count += entry.count;
    group.strategies.set(entry.strategy, (group.strategies.get(entry.strategy) ?? 0) + entry.count);
    groups.set(entry.name, group);
  }
  return [...groups.values()].sort((left, right) => right.count - left.count || left.name.localeCompare(right.name)).map(group => ({ ...group, strategyLabel: [...group.strategies].map(([strategy, count]) => `${strategy || t("wfUncoded")} ${count}`).join(" · ") }));
});
const filteredGroups = computed(() => { const query = groupSearch.value.trim().toLocaleLowerCase(); return grouped.value.filter(group => !query || group.name.toLocaleLowerCase().includes(query) || group.strategyLabel.toLocaleLowerCase().includes(query)); });
const virtualizer = useVirtualizer<HTMLElement, HTMLDivElement>(computed(() => ({ count: filteredGroups.value.length, getScrollElement: () => groupViewport.value, estimateSize: () => 64, overscan: 3, getItemKey: index => filteredGroups.value[index]?.name ?? index })));
const virtualRows = computed(() => virtualizer.value.getVirtualItems());
const totalSize = computed(() => virtualizer.value.getTotalSize());
const measureRow = (element: unknown) => { if (element instanceof HTMLDivElement) virtualizer.value.measureElement(element); };
const totalBase = computed(() => denominator.value === "confirmed" ? props.summary.confirmed : props.summary.total);
const percentage = (count: number) => totalBase.value ? Math.round(count / totalBase.value * 1000) / 10 : 0;
const chartGroups = computed(() => grouped.value.slice(0, 12));
const displayName = (name: string) => name || t("wfUnnamedTranslation");
function chooseMerge(name: string) {
  if (!props.writable || props.busy) return;
  if (mergeFrom.value === null) { mergeFrom.value = name; return; }
  if (mergeFrom.value === name) { mergeFrom.value = null; return; }
  const from = mergeFrom.value; mergeFrom.value = null; emit("merge", from, name);
}
</script>

<template>
  <section class="research-groups" :aria-label="t('wfGroupsDistributionAria')">
    <div class="groups-list"><header><h3>{{ t('wfMergeTranslations') }}</h3><span>{{ t('wfGroupTotals', { p0: summary.total, p1: summary.confirmed, p2: summary.pending }) }}</span><button v-if="activeGroup !== null" type="button" :disabled="busy" @click="emit('filter', null)">{{ t('wfClearGroupFilter') }}</button></header><div class="groups-search"><input v-model="groupSearch" type="search" :aria-label="t('wfFindGroup')" :placeholder="t('wfFindGroupPlaceholder')" /><span v-if="activeGroup !== null">{{ t('wfCurrentNamed', { p0: displayName(activeGroup) }) }}</span></div><p v-if="mergeFrom !== null" class="merge-intent" role="status">{{ t('wfMergeIntent', { p0: displayName(mergeFrom) }) }}<button type="button" @click="mergeFrom = null">{{ t('wfCancel') }}</button></p><div ref="groupViewport" class="groups-viewport"><div :style="{ height: `${totalSize}px`, position: 'relative' }"><div v-for="row in virtualRows" :key="String(row.key)" :ref="measureRow" :data-index="row.index" class="group-row" :class="{ selected: filteredGroups[row.index]?.name === activeGroup }" :style="{ position: 'absolute', top: 0, left: 0, width: '100%', transform: `translateY(${row.start}px)` }"><template v-if="filteredGroups[row.index]"><button type="button" class="group-filter" :disabled="busy" @click="emit('filter', filteredGroups[row.index]!.name)"><strong>{{ displayName(filteredGroups[row.index]!.name) }}</strong><small>{{ t('wfItemsCount', { p0: filteredGroups[row.index]!.count }) }} · {{ filteredGroups[row.index]!.strategyLabel }}</small></button><button type="button" class="merge-button" :disabled="busy || !writable" :aria-label="mergeFrom === null ? t('wfChooseMergeSource', { p0: displayName(filteredGroups[row.index]!.name) }) : t('wfMergeIntoAria', { p0: displayName(mergeFrom), p1: displayName(filteredGroups[row.index]!.name) })" @click="chooseMerge(filteredGroups[row.index]!.name)">{{ t(mergeFrom === null ? 'wfMergeEllipsis' : mergeFrom === filteredGroups[row.index]!.name ? 'wfCancel' : 'wfMergeInto') }}</button></template></div></div><p v-if="!filteredGroups.length" class="groups-empty">{{ t(grouped.length ? 'wfNoMatchingGroups' : 'wfGroupsAfterConfirm') }}</p></div><div v-if="summary.suggestions.length" class="group-suggestions"><div v-for="suggestion in summary.suggestions.slice(0, 5)" :key="`${suggestion.left_group}:${suggestion.right_group}`"><span>{{ t('wfMergeSuggestion', { p0: displayName(suggestion.left_group), p1: displayName(suggestion.right_group) }) }}<small>{{ suggestion.reason }}</small></span><button type="button" :disabled="busy || !writable" @click="emit('merge', suggestion.left_group, suggestion.right_group)">{{ t('wfMerge') }}</button></div><small v-if="summary.suggestions.length > 5">{{ t('wfFirstFiveSuggestions') }}</small></div><p class="groups-help">{{ t('wfMergePreserves') }}</p></div>
    <div class="groups-distribution"><header><h3>{{ translationLabel || t('wfCurrentTranslation') }} · {{ t('wfTranslationDistribution') }}</h3><label>{{ t('wfDenominator') }}<select v-model="denominator" :aria-label="t('wfDistributionDenominator')"><option value="confirmed">{{ t('wfConfirmedCount', { p0: summary.confirmed }) }}</option><option value="all">{{ t('wfAllHitsCount', { p0: summary.total }) }}</option></select></label></header><p>{{ t('wfDistributionHint') }}</p><div class="distribution-bars"><button v-for="group in chartGroups" :key="group.name" type="button" :disabled="busy" :aria-label="t('wfViewExamplesAria', { p0: displayName(group.name), p1: percentage(group.count) })" @click="emit('filter', group.name)"><span>{{ displayName(group.name) }}</span><span class="bar-track"><span :style="{ width: `${Math.min(percentage(group.count), 100)}%` }"></span></span><strong>{{ percentage(group.count) }}%</strong></button></div><p v-if="!chartGroups.length" class="groups-empty">{{ t('wfNoConfirmedTranslations') }}</p><p v-if="grouped.length > 12">{{ t('wfTopTwelveGroups', { p0: grouped.length }) }}</p><p v-if="denominator === 'all' && summary.pending">{{ t('wfPendingNotGrouped', { p0: summary.pending }) }}</p></div>
  </section>
</template>

<style scoped>
.research-groups { display: grid; grid-template-columns: minmax(270px, 1fr) minmax(270px, 1fr); gap: 20px; min-height: 180px; @apply text-ink-900; }.groups-list, .groups-distribution { min-width: 0; }header { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; margin-bottom: 9px; }h3 { font-size: 13px; margin: 0; }header > span, .groups-search > span { font-size: 10px; @apply text-ink-500; }button, input { font: inherit; font-size: 11px; @apply text-ink-900; }button { min-height: 29px; padding: 4px 8px; border: 1px solid var(--line); border-radius: 5px; @apply bg-raised; cursor: pointer; }button:disabled { opacity: .55; cursor: default; }input { padding: 6px; border: 1px solid var(--line); border-radius: 5px; @apply bg-input; min-width: 0; }.groups-search { display: flex; align-items: center; flex-wrap: wrap; gap: 8px; margin-bottom: 7px; }.groups-search input { flex: 1; }.groups-viewport { height: 164px; overflow: auto; border: 1px solid var(--line); border-radius: 7px; }.group-row { display: flex; align-items: center; min-height: 64px; padding: 4px 8px; gap: 8px; border-bottom: 1px solid var(--line); box-sizing: border-box; }.group-row.selected { @apply bg-green-soft; }.group-filter { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 5px; text-align: left; padding: 5px 0; border: 0; background: transparent; }.group-filter strong { font-weight: 500; overflow-wrap: anywhere; }.group-filter small { @apply text-ink-500; line-height: 1.5; overflow-wrap: anywhere; }.merge-button { flex: none; }.merge-intent, .groups-help, .groups-distribution > p { font-size: 10px; @apply text-ink-500; line-height: 1.7; margin: 7px 0; }.merge-intent button { margin-left: 6px; }.group-suggestions > div { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 8px; margin-top: 6px; border-radius: 6px; @apply bg-green-soft; font-size: 11px; }.group-suggestions small { display: block; font-size: 10px; @apply text-ink-500; margin-top: 3px; }.groups-distribution label { margin-left: auto; font-size: 10px; }.groups-distribution select { margin-left: 5px; }.distribution-bars { display: grid; gap: 6px; }.distribution-bars > button { display: grid; align-items: center; grid-template-columns: minmax(65px, 24%) 1fr 42px; gap: 8px; border: 0; padding: 3px 0; background: transparent; text-align: left; }.distribution-bars > button > span:first-child { overflow-wrap: anywhere; }.distribution-bars strong { font-size: 10px; font-weight: 500; text-align: right; }.bar-track { height: 7px; @apply bg-green-soft; border-radius: 5px; overflow: hidden; }.bar-track > span { display: block; height: 100%; border-radius: 5px; @apply bg-accent; }.groups-empty { padding: 18px; @apply text-ink-500; font-size: 11px; line-height: 1.7; }
</style>
